# Generated by Django 4.1 on 2022-08-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_order_product_user_email_shippingaddress_orderitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userName',
            new_name='username',
        ),
    ]
